### ISSUE TITLE
Refactor exception handling of database reconciler

### ISSUE THREAD

**Issue by xrow** [stolostron/multicluster-global-hub#1265]
Dear @ldpliu, 

I am currently installing the multicluster-global-hub version 1.3.1, but it doesn`t install. If I would know what the TRUE error is, I might have a clue what is going on and can fix it. I installed it on OCP 4.14.

The my believe this line of code needs refactoring 
https://github.com/stolostron/multicluster-global-hub/blob/d9b36f65acbf0772355a14c8428b7ea28008acbc/operator/pkg/controllers/storage/storage_reconciler.go#L295

It looks like the err is not properly handled.

See my screenhot.

![image](https://github.com/user-attachments/assets/549785b6-75d3-4462-8e4f-29b29aaad375)

**Comment by ldpliu** [comment]
Thanks @xrow , I have submitted a pr to main branch. 
This line is only used to print info for user. 
For 1.3.1, it's not a high priority issue, so I think it's not necessary to cherry-pick it to release-2.12.

**Comment by xrow** [comment]
@ldpliu Thanks, I was more thinking abou this problem over the weekend. I think, I have not found the root cause. To my believe the instatller hangs after the successfull db connection.

**Comment by xrow** [comment]
Also true no need to backport.

**Comment by ldpliu** [comment]
@xrow 
Please help to check the postgres pod log error and secret `multicluster-global-hub-postgres`
We use https://github.com/stolostron/multicluster-global-hub/blob/release-2.12/operator/pkg/controllers/hubofhubs/storage/postgres_statefulset.go#L125 to build the connection.

**Comment by xrow** [comment]
I found my real cause the amq operator was not availalbe. TY.
