### ISSUE TITLE
Replace global hub transport with cloudevents

### ISSUE THREAD

**Issue by yanmxa** [stolostron/multicluster-global-hub#310]
## 1. Kafka offset committer in Global Hub manager

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/19286664/215428563-a43d3a3d-d173-4e25-84a3-65be927e168f.png">

When the global hub manager receives a message through transport, there is not only a goroutine for the consumer client but also a committer goroutine that commits the Kafka offset periodically. The consumer receives the message and forwards it to the message handler to process the message, after processing the message, the committer updates the offset in Kafka. The process of consuming messages and committing the offset is asynchronous.

But when we use cloudevents to deliver messages, although based on Kafka protocol, we cannot directly update the offset through the Kafka client after receiving the message. Instead, the cloudevents client receives the message and [returns an ACK or NACK result](https://github.com/cloudevents/sdk-go/blob/885b9ca529f0bdf9c2c139b607bc5888527d8013/v2/client/receiver.go#L102) to decide whether to update the [kafka offset](https://github.com/cloudevents/sdk-go/blob/885b9ca529f0bdf9c2c139b607bc5888527d8013/protocol/kafka_sarama/v2/receiver.go#L71). The message consuming and the offset updating are synchronous in the whole process.

Now the question are:
1. The above two ways manual commit kafka offset, so that when the consumer crashes and restarts, it can continue to consume the previously received messages. Is this manual commit offset method necessary in global hub?
2. If we use cloudevents, what are the possible impacts of synchronously updating the Kafka offset on the global hub?
3. Do these effects really prevent us from using cloudevents instead of the original transport?

**Comment by yanmxa** [comment]
## Transport Spec
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/19286664/215660818-56673674-17a0-4cf6-a416-2a6b6f2b5645.png">

### Updates: 
1. Transport **Producer**: reduce methods of the producer interface
2. Transport **Consumer**: only responsible for delivering messages, not handling bundle-related logic
3. **Global Hub Agent**: add a dispatcher to register syncers for different bundles, and dispatch messages to the corresponding syncer according to the received message ID

**Comment by nirrozenbaum** [comment]
I see @vMaroon has assigned himself. he was in charge of the initial Kafka work, so he probably has the best answers.
having said that, If I remember correctly I think we had discussions about cloud events when we started the collaboration and we agreed that it should be possible in the spec path, but will have some issues in the status path.

@yanmxa continuing the other thread we discussed about performance, this is correct here as well.
in the status path, we need to keep in mind that the scale is extremely high, 1M MCs and 100M policies status updates.
we intentionally separated the offset commit to a different goroutine, in order to achieve the best performance we can get.
if we'll have to commit offset synchronously after every bundle processing, it will slow the process rate and of course as a result will reduce the performance.

As I suggested in the different thread we discussed, I suggest here as well to try running high scale simulations in order to understand the huge performance effect a change can make (it's true about any change, not this one specifically). 
it's highly important in order to understand which changes are acceptable and which aren't.
   
here are the original performance results we were able to achieve:
  
![image](https://user-images.githubusercontent.com/19717747/216059035-b49860bb-7b48-4a9b-adf6-8e57e622faaf.png)

**Comment by nirrozenbaum** [comment]
high scale simulations setup:

![image](https://user-images.githubusercontent.com/19717747/216062051-298dc35d-74e7-4c34-a6f0-4eddd9859181.png)

**Comment by vMaroon** [comment]
As @nirrozenbaum mentioned, regardless of what we say here, any substantial change to the status-path flow should be followed with a set of high scale tests, otherwise it would not be right to claim the same scalability as the system underwent iterations of improvements and compactions to achieve a very efficient and compact data flow.

1. The first major issue in the proposition is synchronous reading from Kafka: 
    - Since the conflation-logic is a consumer of the transport through go-channels, means that synchronous reading from Kafka would propagate all the way to the conflators, unless you decouple them with a middle-layer of conflation, which is a recursive problem.
    - Regardless, at high scale, it is against best practices to go for synchronous, please keep in mind that the demand here is of 100k+ managed clusters, and the natural next step is to go for 1M+ and so on - and the current design supports more than 1M+.

2. Cloud-events: if it is beyond structuring a message, keep the following in mind:
    1. Delta messages: while the tests showed that the system can still manage extreme scales without the delta-messaging mechanism, the bandwidth required is considerably larger. Therefore delta-messages should not be dropped.
    2. Message fragmentation: with the Kafka message size limit being 1MB, the transport layer manages fragmentation transparently, while satisfying one of the major assumptions of **messages committed are certainly processed (or irrelevant) - as compactly as possible**.
        -  This means, on the same Kafka partition, there can be multiple open streams of fragmented messages, and their offsets are changed such that if two or more streams intersect, committing one when complete then crashing does not cause loss of fragments of the rest of the intersected streams.
        
The above are the tips of each point, if requested, I can dive into reasoning and more details.

**Comment by yanmxa** [comment]
@vMaroon Very much appreciate your information! 
1. As you said, the main purpose of using `delta messages` here is to reduce bandwidth.
2. The way `message fragmentation` is used to assemble messages and then commit message offset asynchronously is very clever. I had to think about how to deliver and consume chunked messages in `cloudevents`.
3. I am doing a simple `A/B test`, just synchronizing managed clusters from leaf hub to hub of hubs database. cloud you help to check the following test result to see if it is reasonable? and I will append the test data of `cloudevents` later when I finish it.
      - Before using `cloudevents`
           - Time to load 100K MCs(100 LFs with 1000 MCs) to HoH: 4 seconds
           - Time to load 1M MCs(1000 LFs with 1000 MCs) to HoH: 49 seconds

**Comment by yanmxa** [comment]
## Transport Spec Path
<img width="628" alt="image" src="https://user-images.githubusercontent.com/19286664/217704715-7fd5f6c2-d00a-4fbb-aaac-791c1a2b302f.png">

### Updates: 
1. Transport **Producer**: reduce methods of the producer interface
2. Transport **Consumer**: only responsible for delivering messages, not handling bundle-related logic
3. **Global Hub Agent**: add a dispatcher to register syncers for different bundles, and dispatch messages to the corresponding syncer according to the received message ID

## Transport Status Path
<img width="863" alt="image" src="https://user-images.githubusercontent.com/19286664/217704775-4926b795-603d-49fc-81ff-04f656c67e0c.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/19286664/217746352-0115cd5f-4315-4096-b9c2-bf10152fc6e8.png">

### Updates
1. Transport **Producer**: reduce methods of the producer interface, the status producer is consistent with the interface of the spec.
2. Transport **Consumer**: align with the spec consumer. It's only responsible for receiving and forwarding messages, not for processing messages
  - Bundle syncers don't need to be registered to a specific consumer. Add a **TransportDispatcher** so that the consumer only forwards the message to the dispatcher, which invokes the registered `syncer` for processing based on the `MsgID`.
  - Remove the asynchoronous offset **committer**. The `cloudevents` client receives the message and [returns an ACK or NACK result](https://github.com/cloudevents/sdk-go/blob/885b9ca529f0bdf9c2c139b607bc5888527d8013/v2/client/receiver.go#L102) to decide whether to update the [kafka offset](https://github.com/cloudevents/sdk-go/blob/885b9ca529f0bdf9c2c139b607bc5888527d8013/protocol/kafka_sarama/v2/receiver.go#L71). The message offset updating are synchronous in the process.
  
  ## A/B Testing
  Synchronize managed clusters from Regional Hubs to Global Hub database.
  ### 100 MCs: 100 RHs  with 1000 MCs
| Scenarioes\Times |  1  |   2  |  3  |
| ------ | ------ | ------ | ----- | 
| Kafka | 4 seconds | 4 seconds | 4 seconds |
| Cloudevents | 3 seconds | 6 seconds | 4 seconds |

### 1M MCs: 1000 RHs  with 1000 MCs
| Scenarioes\Times |  1  |   2  |  3  |
| ------ | ------ | ------ | ----- | 
| Kafka | 49 seconds | 47 seconds | 48 seconds |
| Cloudevents | 59 seconds | 57 seconds | 60 seconds |

## Improvements
1. Increase the size of messages that can be sent at a time.
2. Since the message is sent in chunks, the manager consumer locks the receiver when assembling chunks after receiving the event. Reducing the use of locks should reduce the delivery time.

**Comment by yanmxa** [comment]
## Test Results after Increasing Transport Limit Size

### 1M MCs: 1000 RHs  with 1000 MCs
| Scenarioes\Times |  1  |   2  |  3  |
| ------ | ------ | ------ | ----- | 
| Kafka |  54 seconds | 55 seconds | 53 seconds |
| Cloudevents(kafka) | 51 seconds | 50 seconds | 52 seconds |

**Conclusion**: From the test results so far, using cloudevents to replace the original transport does not cause significant performance degradation

**Comment by vMaroon** [comment]
@yanmxa these results seem fine on the first look. Did you try testing the load / rotation of 100 policies with the setup above? It's highly suggested to do so.

**Comment by yanmxa** [comment]
@vMaroon I did not test poicy. What I want to focus on here is the impact of different transport types on data transmission, so I simply transferred Mnanaged cluster to compare the differences between the cloudevents and kafka.

**Comment by yanmxa** [comment]
@vMaroon Since we focus on the performance change of transport, I only compare and test the cases of 1 M Polices and 1 M managed cluster in HoH initialization.

- 10 Policies
- 100 RHs with 1000 MCs
- **Total**: 100 K MCs and 1 M Policies

Scenarioes\Times | 1 | 2 | 3
-- | -- | -- | --
Kafka | 12 seconds | 15 seconds | 13 seconds
Cloudevents(kafka) | 18 seconds | 16 seconds | 12 seconds

**Comment by yanmxa** [comment]
ref: https://github.com/cloudevents/sdk-go/issues/846

**Comment by yanmxa** [comment]
For the transport status path, we added a `transportFormt` in the API to support both kafka directly and cloudevents.
