### ISSUE TITLE
Include Stolostron icon in OpenShift catalog

### ISSUE THREAD

**Issue by sarroutbi** [stolostron/multicluster-global-hub#696]
It seems that this operator does not show any icon on OpenShift catalog:

![image](https://github.com/stolostron/multicluster-global-hub/assets/959277/9c41ed62-2ecd-4eb6-b9da-989351d35d53)

It would be great to show one (Stolstron for example)

**Comment by clyang82** [comment]
@sarroutbi Did you log the issue in wrong repo?

**Comment by sarroutbi** [comment]
It might be ... I will close it. Sorry for confusion
