### ISSUE TITLE
Investigate the agent memory consumption

### ISSUE THREAD

**Issue by clyang82** [stolostron/multicluster-global-hub#743]
if the cluster is not a hub cluster, the agent will be running without any errors. the cpu and memory consumption
`multicluster-global-hub-agent-79684bcdfd-zkq6z   1m           59Mi`
if the cluster is a hub cluster, the consumption is 
`multicluster-global-hub-agent-79684bcdfd-k5cdz   8m           131Mi`

Need to understand the contribution for this consumption.

**Comment by yanmxa** [comment]
<img width="1495" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/884cca29-30c1-4a63-af40-50aa030614c3">

The total memory is still about 60 MB
<img width="1094" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/3e691da6-78cc-4fa5-b29e-c1d56de58a18">

<img width="940" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/485005c2-56d6-43cc-a38b-34131c85114a">

Seems the usage is still smoothly without a memory leak, still waiting abnormal fluctuations[2024-03-20 10:00 AM]

**Comment by yanmxa** [comment]
<img width="836" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/8f2958df-4af9-46bd-b521-eee5f6eea944">

It has been stable at around 60MB [2024-03-21 09:50 AM]

**Comment by yanmxa** [comment]
<img width="1002" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/0d81fd5f-3b59-47c7-aed6-8ee063c8462b">

**Comment by yanmxa** [comment]
```bash
kubectl exec -it multicluster-global-hub-agent-68765b4495-sscnm -n multicluster-global-hub-agent -- sh
sh-4.4$ cat /sys/fs/cgroup/memory.current
314957824
sh-4.4$
```

<img width="738" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/721c876b-181b-4f50-b0ba-c3336100efbc">

**Comment by yanmxa** [comment]
Max CPU: 100 ms = 100,000(us)/1,000
```bash
sh-4.4$ cat /sys/fs/cgroup/cpu.max
max 100000
```
Current Memory: 270,95 MB = 284188672/(1024*1024)
Max Memory: 1000 MB = 
```bash
sh-4.4$ cat /sys/fs/cgroup/memory.current
284188672
sh-4.4$ cat /sys/fs/cgroup/memory.max
1048576000
```

**Comment by yanmxa** [comment]
After a few days, the agent memory keeps on `298 MB`

```bash
sh-4.4$ cat /sys/fs/cgroup/memory.current
313012224
```
