### ISSUE TITLE
fix the sonarcloud security issue

### ISSUE THREAD

**Issue by clyang82** [stolostron/multicluster-global-hub#896]
<img width="1228" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/7711311/a3450e34-02ad-4644-8c97-8f1f6eac339b">

/assign @ldpliu

**Comment by yanmxa** [comment]
Is this issue fixed @ldpliu ?

**Comment by ldpliu** [comment]
Yes, The latest main branch has no security issue: https://sonarcloud.io/project/security_hotspots?id=open-cluster-management_hub-of-hubs
