### ISSUE TITLE
Re-think the tests

### ISSUE THREAD

**Issue by yanmxa** [stolostron/multicluster-global-hub#972]
## TEST Dir
- test
  - e2e
  - integration
  - manifest
  -  script
     - util.sh
     - e2e_*.sh
     - intergration_*.sh
    
### Setup workflow
<img width="961" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/19286664/f7af1021-187a-48e5-9709-28f884487791">

### Test cases
- place all the e2e test scripts in one place `test/scripts/e2e_*.sh`
- remove the `e2e-test-validation`, it overlaps with the `beforAll` of the `suite`
- remove the duplicated test case between `e2e-test-placement` and `e2e-test-policy(localpolicy)`, `e2e-test-app`
- consolidate the environment setup: https://github.com/stolostron/multicluster-global-hub/pull/957
- https://github.com/stolostron/multicluster-global-hub/pull/970
  ```bash
  $ tree -L 2 test
  test
  ├── e2e
  │   ├── application_test.go
  │   ├── ...
  │   ├── suite_test.go
  │   └── utils
  ├── integration
  │   ├── agent
  │   ├── manager
  │   ├── operator
  │   └── pkg
  ├── Makefile
  ├── manifest
  │   ├── app
  │   └── ...
  └── script
      ├── config
      ├── e2e_cleanup.sh
      ├── ...
      ├── e2e_setup.sh
      ├── ocm.sh
      └── util.sh
  ```

### Components

```bash
$ tree -L 1 test/integration
test/integration
├── agent
├── manager
├── operator
└── pkg
```

#### Agent
  - spec: deploy resource to managed hub cluster
  - status: report the resource status
  - controller: CRD, Cert and Clusterclaim(TODO)
  - code: https://github.com/stolostron/multicluster-global-hub/pull/975
    ```bash
    $ tree -L 2 test/integration/agent
    test/integration/agent
    ├── controller
    │   ├── ...
    │   └── suite_test.go
    ├── spec
    │   ├── ...
    │   └── suite_test.go
    └── status
        ├── application_test.go
        ├── ...
        ├── placement_test.go
        └── suite_test.go
    ```

#### Manager
- code: https://github.com/stolostron/multicluster-global-hub/pull/979

  ```bash
  tree -L 1 test/integration/manager
  test/integration/manager
  ├── api
  ├── controller
  ├── spec
  ├── status
  └── webhook
  ```

#### Operator
- code: https://github.com/stolostron/multicluster-global-hub/pull/982
  ```bash
  tree -L 1 test/integration/operator
  test/integration/operator
  ├── addon
  └── controller
  ```

#### ~Pkg~

  ```bash
  tree -L 1 test/integration/pkg
  test/integration/pkg
  ├── manifest
  └── transport
  ```
- https://github.com/openshift/release/pull/53448

### Middleres
- envtest
- embedded Postgres
- cloudevent chan protocol - use this for the manager and agent transport, don't need to start the backend processes
- confluent - mock kafka

### Concerns

1. Code coverage by the integration? - https://github.com/openshift/release/pull/53275

**Comment by clyang82** [comment]
other points for e2e:
1. Make sure that clean-up the environment after the case is finished.
2. add grafana e2e test

points for integration test:
1. leverage the same DB instance for all cases. ensure the tables are cleaned up once the test is done.
2. Do not start the controller reconciler directly. instead, test the functions one by one. start the reconciler may lead some unnecessary logs output and abnormal behaviour.
3. Look at https://github.com/kubernetes-sigs/controller-runtime/tree/main/tools/setup-envtest to correct our usage.
